# Generated by Django 4.1.3 on 2023-01-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='profit_loss',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
