# Generated by Django 4.1.3 on 2023-01-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_bill_profit_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='sold_on',
            field=models.DateField(null=True),
        ),
    ]
